marks=[]
f1=int(input("Enter marks for student1"))
marks.append(f1)
f2=int(input("Enter marks for student2"))
marks.append(f2)
f3=int(input("Enter marks for student3"))
marks.append(f3)
f4=int(input("Enter marks for student4"))
marks.append(f4)
f5=int(input("Enter marks for student5"))
marks.append(f5)
marks.sort()
print(marks)